name: Flutter CI

on:
  push:
    branches: [ "**" ]
  pull_request:
    branches: [ "**" ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: mobile_app
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Flutter version
        run: flutter --version

      - name: Install dependencies
        run: flutter pub get

      - name: Analyze
        run: flutter analyze --no-pub

      - name: Run tests
        run: flutter test --no-pub

      - name: Build APK (debug)
        run: flutter build apk --debug --no-pub


